---
# https://wiki.debian.org/SSDOptimization
# https://wiki.archlinux.org/index.php/Solid_State_Drives

- name: ensure deadline scheduler for ssd drives are enabled
  copy: src=60-schedulers.rules dest=/etc/udev/rules.d/

# ' ext4 defaults ' -> ' ext4    defaults,noatime,discard '
- name: add discart,noatime to /etc/fstab for ext4
  replace:
    dest: /etc/fstab
    regexp: '\sext4\s*defaults\s'
    replace: ' ext4    defaults,noatime,discard '

# 'issue_discards = 0' -> 'issue_discards = 1'
- name: add issue_discards = 1 to /etc/lvm/lvm.conf
  replace:
    dest: /etc/lvm/lvm.conf
    regexp: 'issue_discards\s=\s0'
    replace: 'issue_discards = 1'
