---
- name: update all packages
  dnf: name=* state=latest

- name: ensure packages is installed
  dnf: name={{ item }} state=latest
  with_items:
    - NetworkManager-pptp-gnome
    - Zim
    - docker
    - docker-compose
    - firefox
    - gimp
    - git
    - gnome-disk-utility
    - google-droid-sans-fonts
    - google-droid-sans-mono-fonts
    - google-droid-serif-fonts
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-extras
    - gstreamer1-vaapi
    - gvfs-mtp
    - gvfs-smb
    - keepassx
    - kupfer
    - libreoffice
    - libreoffice-langpack-ru
    - libselinux-python
    - makepasswd
    - mc
    - mysql-connector-python
    - nmap
    - numlockx
    - p7zip
    - p7zip-plugins
    - pidgin
    - pidgin-libnotify
    - postgresql
    - python-psycopg2
    - slock
    - stow
    - strace
    - thunderbird
    - tmux
    - vim
    - vinagre
    - wireshark
    - xautolock
    - xkb-switch
  notify:
    - enable docker service

- name: ensure packages is removed
  dnf: name={{ item }} state=absent
  with_items:
    - nano

- name: add docker system group
  group: name=docker system=yes state=present

- name: add user to docker group
  user: name=pod groups=docker append=yes

- name: enable global fonts settings
  copy: src=etc_fonts_local.conf dest=/etc/fonts/local.conf

- name: enable unicode font for tty
  copy: src=etc_vconsole.conf dest=/etc/vconsole.conf

- name: enable sshd socket
  service: name=sshd.socket enabled=yes

- name: start sshd socket
  service: name=sshd.socket state=started
