---
- name: update all packages
  dnf: name=* state=latest

- name: enable rpmfusion-free repo
  dnf: name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-22.noarch.rpm disable_gpg_check=yes

- name: enable rpmfusion-nonfree repo
  dnf: name=http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-22.noarch.rpm disable_gpg_check=yes

- name: install packages
  dnf: name={{ item }} state=latest
  with_items:
    - docker
    - freetype-freeworld
    - geary
    - git
    - gnome-tweak-tool
    - google-droid-sans-fonts
    - google-droid-sans-mono-fonts
    - google-droid-serif-fonts
    - gstreamer1-libav
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-extras
    - gstreamer1-plugins-ugly
    - gstreamer1-vaapi
    - mc
    - mysql-connector-python
    - nmap
    - p7zip
    - p7zip-plugins
    - pidgin
    - postgresql
    - python-psycopg2
    - stow
    - strace
    - tmux
    - vim
  notify:
    - enable docker service

- name: add docker system group
  group: name=docker system=yes state=present

- name: add user to docker group
  user: name=pod groups=docker append=yes

- name: enable global fonts settings
  copy: src=etc_fonts_local.conf dest=/etc/fonts/local.conf
