---
- name: update all packages
  dnf: name=* state=latest

- name: install packages
  dnf: name={{ item }} state=latest
  with_items:
    - docker
    - docker-compose
    - firefox
    - git
    - google-droid-sans-fonts
    - google-droid-sans-mono-fonts
    - google-droid-serif-fonts
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-extras
    - gstreamer1-vaapi
    - keepassx
    - kupfer
    - libreoffice
    - libreoffice-langpack-ru
    - libselinux-python
    - makepasswd
    - mc
    - mysql-connector-python
    - nmap
    - numlockx
    - p7zip
    - p7zip-plugins
    - pidgin
    - pidgin-libnotify
    - postgresql
    - python-psycopg2
    - slock
    - stow
    - strace
    - thunderbird
    - tmux
    - vim
    - vinagre
    - wireshark
    - xautolock
    - xkb-switch
    - Zim
  notify:
    - enable docker service

- name: add docker system group
  group: name=docker system=yes state=present

- name: add user to docker group
  user: name=pod groups=docker append=yes

- name: enable global fonts settings
  copy: src=etc_fonts_local.conf dest=/etc/fonts/local.conf

- name: enable unicode font for tty
  copy: src=etc_vconsole.conf dest=/etc/vconsole.conf

- name: ensure ~/.config/bash directory exist
  file: path=/home/pod/.config/bash state=directory
