---
- name: ensure oracle repository gpg key is present
  rpm_key: key=https://www.virtualbox.org/download/oracle_vbox.asc state=present

- name: enable oracle repository file
  get_url:
    url: 'http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo'
    dest: '/etc/yum.repos.d/virtualbox.repo'

- name: install virtualbox
  dnf: name={{ item }} state=latest
  with_items:
  - dkms
  - kernel-devel
  - kernel-headers
  - VirtualBox-5.1

