---
- name: enable rpmfusion-free repo
  dnf: name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-23.noarch.rpm disable_gpg_check=yes

- name: enable rpmfusion-nonfree repo
  dnf: name=http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-23.noarch.rpm disable_gpg_check=yes

- name: install packages
  dnf: name={{ item }} state=latest
  with_items:
    - freetype-freeworld
    - gstreamer1-libav
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-ugly
