---
- name: enable rpmfusion-free and rpmfusion-nonfree repos
  dnf: name={{ item }} disable_gpg_check=yes
  with_items:
  - 'http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-25.noarch.rpm'
  - 'http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-25.noarch.rpm'

- name: install packages
  dnf: name={{ item }} state=latest
  with_items:
  - freetype-freeworld
  - gstreamer1-libav
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-ugly

