---
- name: enable rpmfusion-free and rpmfusion-nonfree repos
  dnf: name={{ item.url }} disable_gpg_check=yes
  with_items:
    - { url: 'http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-23.noarch.rpm' }
    - { url: 'http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-23.noarch.rpm' }

- name: install packages
  dnf: name={{ item }} state=latest
  with_items:
    - freetype-freeworld
    - gstreamer1-libav
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-ugly
