---
- hosts: 127.0.0.1
  connection: local
  become: yes

  roles:
  - role: fedora
  - role: fedora-rpmfusion
  - role: fedora-tierpod-packages
  - { role: ssd, tags: ssd }
  - { role: fedora-virtualbox, tags: virtualbox }
