---
- hosts: 127.0.0.1
  connection: local
  sudo: yes

  roles:
    - role: fedora-xfce-spin
    - role: fedora
    - role: fedora-rpmfusion
    - role: fedora-tierpod-packages
    - { role: ssd, tags: ssd }
    - { role: fedora-virtualbox, tags: virtualbox }
