---
- name: enable tierpod/personal-packages
  shell: dnf copr enable tierpod/personal-packages -y
  args:
    creates: /etc/yum.repos.d/_copr_tierpod-personal-packages.repo

- name: enable tierpod/gtk2-without-tooltip-patch
  shell: dnf copr enable tierpod/gtk2-without-tooltip-patch -y
  args:
    creates: /etc/yum.repos.d/_copr_tierpod-gtk2-without-tooltip-patch.repo

- name: install packages
  dnf: name={{ item }} state=latest
  with_items:
  - gtk2
  - pidgin-toolbar-shrink
  - ubuntu-font-family
